# Generated by Django 5.2.9 on 2025-12-26 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('bar', 'Бар'), ('shop', 'Магазин'), ('other', 'Другое')], max_length=16)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='places.place')),
            ],
        ),
    ]
