# Generated by Django 5.2.9 on 2025-12-07 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_intensity', models.CharField(choices=[('low', 'Спокойно'), ('medium', 'Норм'), ('high', 'Жёстко')], default='medium', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('people_count', models.PositiveIntegerField(default=1)),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('intensity', models.CharField(choices=[('low', 'Спокойно'), ('medium', 'Нормально'), ('high', 'Жёстко')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.scenario')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
