# Generated by Django 5.2.9 on 2025-12-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='default_intensity',
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_hours',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='people_count',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
