# Generated by Django 5.2.9 on 2025-12-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_scenario_default_intensity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_code', models.CharField(blank=True, help_text="Код напитка (например 'wine' или 'champagne'), можно оставить пустым для общих советов.", max_length=50)),
                ('kind', models.CharField(choices=[('drink', 'Напиток'), ('food', 'Блюдо'), ('other', 'Другое')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='events.scenario')),
            ],
        ),
    ]
