# Generated by Django 5.2.9 on 2025-12-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_scenariosuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('drinks', models.ManyToManyField(blank=True, related_name='dishes', to='events.drink')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='drinks',
            field=models.ManyToManyField(blank=True, related_name='scenarios', to='events.drink'),
        ),
        migrations.DeleteModel(
            name='ScenarioSuggestion',
        ),
    ]
