# Generated by Django 5.2.9 on 2025-12-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_drink_dish_scenario_drinks_delete_scenariosuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Крепость в % об.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='strength',
            field=models.CharField(choices=[('strong', 'Крепкий'), ('regular', 'Обычный'), ('non_alcoholic', 'Безалкогольный')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drinks', to='events.drinkcategory'),
        ),
        migrations.AddField(
            model_name='drink',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='drinks', to='events.drinktag'),
        ),
    ]
