# Generated by Django 5.2.9 on 2025-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_drinkcategory_drinktag_drink_abv_drink_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Очень просто'), ('medium', 'Средне'), ('hard', 'Посложнее')], default='easy', max_length=10),
        ),
    ]
