# Generated by Django 5.2.9 on 2025-12-07 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_dish_event_drink_event_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Когда примерно был напиток.')),
                ('volume_ml', models.PositiveIntegerField(help_text='Объём напитка в миллилитрах, например 150.')),
                ('abv', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Крепость, % об.')),
                ('bac_estimate', models.DecimalField(blank=True, decimal_places=3, help_text='Очень грубая оценка по одной порции, только для справки.', max_digits=5, null=True, verbose_name='Оценка BAC, ‰')),
                ('note', models.CharField(blank=True, help_text='Опциональный комментарий.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alcohol_logs', to='events.drink')),
                ('event', models.ForeignKey(blank=True, help_text='Можно привязать запись к событию, а можно оставить пустым.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alcohol_logs', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcohol_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
    ]
