# Generated by Django 5.2.9 on 2025-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alcohollog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='after_text',
            field=models.TextField(blank=True, help_text='Відновлення: сон, вода, поїсти, не сідати за кермо тощо.'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='during_text',
            field=models.TextField(blank=True, help_text='Що робити під час події: теми розмов, темп пиття, ритм вечора.'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='prep_text',
            field=models.TextField(blank=True, help_text='Рекомендации по подготовке: що купити, що підготувати, атмосфера.'),
        ),
    ]
