# Generated by Django 5.2.9 on 2025-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_scenario_after_text_scenario_during_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe_text',
            field=models.TextField(blank=True, help_text='Короткий рецепт или инструкция для этого блюда.'),
        ),
    ]
