# Generated by Django 5.2.9 on 2025-12-14 15:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_dish_recipe_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('food', 'Еда'), ('other', 'Другое')], default='food', max_length=16)),
                ('default_unit', models.CharField(choices=[('pcs', 'шт'), ('g', 'г'), ('kg', 'кг'), ('ml', 'мл'), ('l', 'л')], default='g', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_person', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('g', 'г'), ('kg', 'кг'), ('ml', 'мл'), ('l', 'л')], default='g', max_length=8)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='events.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_uses', to='events.ingredient')),
            ],
            options={
                'unique_together': {('dish', 'ingredient', 'unit')},
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='dishes', through='events.DishIngredient', to='events.ingredient'),
        ),
    ]
