# Generated by Django 5.2.7 on 2025-12-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_eventparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="category",
            field=models.CharField(
                choices=[
                    ("romantic", "Побачення"),
                    ("sport", "Спорт/Футбол"),
                    ("party", "Вечірка"),
                    ("budget", "Перед зарплатою"),
                    ("friends", "Друзі"),
                    ("family", "Сімейне"),
                    ("holiday", "Свято"),
                    ("other", "Інше"),
                ],
                default="other",
                help_text="Категорія сценарію для фільтрації",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="icon",
            field=models.CharField(
                default="🎉", help_text="Емодзі для відображення", max_length=10
            ),
        ),
    ]
