# Generated by Django 5.2.9 on 2025-12-25 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_scenario_category_scenario_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'ordering': ['-invited_at']},
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='created_at',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Час закінчення події', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='feedback',
            field=models.TextField(blank=True, help_text='Відгук після події'),
        ),
        migrations.AddField(
            model_name='event',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Подія завершена'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_address',
            field=models.CharField(blank=True, help_text='Адреса', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Широта', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Довгота', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(blank=True, help_text='Назва місця', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Час початку події', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Оцінка події від 1 до 5', null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='invited_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Оцінка події від 1 до 5', null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('accepted', 'Прийнято'), ('declined', 'Відхилено'), ('maybe', 'Можливо')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
