# Generated by Django 5.2.9 on 2025-12-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventparticipant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_alcoholic',
            field=models.BooleanField(default=False, verbose_name='Алкогольний'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Дуже просто'), ('medium', 'Середньо'), ('hard', 'Складніше')], default='easy', max_length=10),
        ),
    ]
