# Generated by Django 5.2.9 on 2025-12-26 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_add_notification_response_and_event_features'),
        ('recipes', '0002_add_cocktail_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cocktails',
            field=models.ManyToManyField(blank=True, help_text='Коктейлі для події', related_name='events', to='recipes.cocktail'),
        ),
        migrations.AddField(
            model_name='event',
            name='drinks',
            field=models.ManyToManyField(blank=True, help_text='Напої для події', related_name='multi_events', to='events.drink'),
        ),
        migrations.AlterField(
            model_name='alcohollog',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Міцність, % об.'),
        ),
        migrations.AlterField(
            model_name='alcohollog',
            name='bac_estimate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Дуже груба оцінка по одній порції, тільки для довідки.', max_digits=5, null=True, verbose_name='Оцінка BAC, ‰'),
        ),
        migrations.AlterField(
            model_name='alcohollog',
            name='event',
            field=models.ForeignKey(blank=True, help_text="Можна прив'язати запис до події, а можна залишити порожнім.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alcohol_logs', to='events.event'),
        ),
        migrations.AlterField(
            model_name='alcohollog',
            name='note',
            field=models.CharField(blank=True, help_text='Опціональний коментар.', max_length=255),
        ),
        migrations.AlterField(
            model_name='alcohollog',
            name='taken_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Коли приблизно був напій.'),
        ),
        migrations.AlterField(
            model_name='alcohollog',
            name='volume_ml',
            field=models.PositiveIntegerField(help_text="Об'єм напою в мілілітрах, наприклад 150."),
        ),
        migrations.AlterField(
            model_name='drink',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Міцність у % об.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='strength',
            field=models.CharField(choices=[('strong', 'Міцний'), ('regular', 'Звичайний'), ('non_alcoholic', 'Безалкогольний')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='drink',
            field=models.ForeignKey(blank=True, help_text='Основний напій (застаріле, використовуйте drinks)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.drink'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('food', 'Їжа'), ('other', 'Інше')], default='food', max_length=16),
        ),
    ]
