# Generated by Django 5.2.9 on 2025-12-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_add_drinks_and_cocktails_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dishes',
            field=models.ManyToManyField(blank=True, help_text='Страви для події', related_name='multi_events', to='events.dish'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dish',
            field=models.ForeignKey(blank=True, help_text='Основна страва (застаріле, використовуйте dishes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.dish'),
        ),
    ]
