# Generated by Django 5.2.9 on 2025-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_created_at_remove_profile_updated_at_and_more'),
        ('events', '0008_alcohollog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский'), ('other', 'Другое / не указано')], help_text='Нужно для более точной оценки BAC', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Полных лет', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_scenarios',
            field=models.ManyToManyField(blank=True, related_name='favorite_for_profiles', to='events.scenario'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Рост в см', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Вес в кг, нужен для BAC', max_digits=5, null=True),
        ),
    ]
