# Generated by Django 5.2.9 on 2025-12-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_gender_profile_created_at_profile_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gdpr_consent',
            field=models.BooleanField(default=False, help_text='Согласие на обработку персональных данных.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_adult_confirmed',
            field=models.BooleanField(default=False, help_text='Подтверждение, что пользователю 18+.'),
        ),
    ]
