# Generated by Django 5.2.9 on 2025-12-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_trial_end',
            field=models.DateTimeField(blank=True, help_text='Дата закінчення пробного періоду Premium', null=True),
        ),
    ]
