# Generated by Django 5.2.9 on 2025-12-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_premium_trial_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_tag',
            field=models.CharField(blank=True, help_text='Унікальний тег для запрошення друзів (наприклад #ABC123)', max_length=10, null=True, unique=True),
        ),
    ]
