# Generated by Django 5.2.7 on 2025-12-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_profile_unique_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_notifications",
            field=models.BooleanField(default=True, help_text="Email сповіщення"),
        ),
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("uk", "Українська"), ("en", "English")],
                default="uk",
                help_text="Мова інтерфейсу",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="notifications_enabled",
            field=models.BooleanField(default=True, help_text="Загальні сповіщення"),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_visible",
            field=models.BooleanField(
                default=True, help_text="Профіль видимий для інших"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="push_notifications",
            field=models.BooleanField(default=True, help_text="Push сповіщення"),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_in_leaderboard",
            field=models.BooleanField(
                default=True, help_text="Показувати у таблиці лідерів"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Темна"), ("light", "Світла"), ("auto", "Авто")],
                default="dark",
                help_text="Тема інтерфейсу",
                max_length=10,
            ),
        ),
    ]
