# Generated by Django 5.2.9 on 2025-12-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_email_notifications_profile_language_and_more'),
        ('events', '0016_add_notification_response_and_event_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='response_action',
            field=models.CharField(choices=[('none', 'Без відповіді'), ('accepted', 'Прийнято'), ('declined', 'Відхилено')], default='none', max_length=10),
        ),
    ]
