# Generated by Django 5.2.9 on 2025-12-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_notification_response_and_event_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text="Ім'я, яке бачитимуть інші користувачі", max_length=50),
        ),
    ]
