# Generated by Django 5.2.9 on 2025-12-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_cocktail_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='category',
            field=models.CharField(choices=[('shot', 'Шот'), ('classic', 'Класичний'), ('tiki', 'Тікі'), ('sour', 'Сауер'), ('fizz', 'Фіз'), ('highball', 'Хайбол'), ('martini', 'Мартіні'), ('frozen', 'Заморожений'), ('hot', 'Гарячий'), ('punch', 'Пунш'), ('spritz', 'Шпріц'), ('other', 'Інше')], default='classic', help_text='Тип коктейлю', max_length=20),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='strength',
            field=models.CharField(choices=[('light', 'Легкий (до 10%)'), ('medium', 'Середній (10-20%)'), ('strong', 'Міцний (20-30%)'), ('very_strong', 'Дуже міцний (30%+)'), ('non_alcoholic', 'Безалкогольний')], default='medium', help_text='Міцність коктейлю', max_length=20),
        ),
    ]
