# Generated by Django 5.2.9 on 2025-12-14 15:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0010_dish_recipe_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.PositiveIntegerField(default=4)),
                ('duration_hours', models.PositiveIntegerField(default=4)),
                ('intensity', models.CharField(choices=[('low', 'Низкая'), ('normal', 'Средняя'), ('high', 'Высокая')], default='normal', max_length=16)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists', to='events.event')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists', to='events.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('alcohol', 'Алкоголь'), ('food', 'Еда'), ('water', 'Вода'), ('ice', 'Лёд'), ('other', 'Другое')], default='other', max_length=16)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('ml', 'мл'), ('l', 'л'), ('g', 'г'), ('kg', 'кг')], default='pcs', max_length=8)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('is_auto', models.BooleanField(default=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'ordering': ['category', 'name', 'unit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioSupplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('prep', 'Подготовка'), ('during', 'Во время'), ('recovery', 'Восстановление')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('alcohol', 'Алкоголь'), ('food', 'Еда'), ('water', 'Вода'), ('ice', 'Лёд'), ('other', 'Другое')], default='other', max_length=16)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('ml', 'мл'), ('l', 'л'), ('g', 'г'), ('kg', 'кг')], default='pcs', max_length=8)),
                ('qty_per_person_per_hour', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10)),
                ('is_required', models.BooleanField(default=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_templates', to='events.scenario')),
            ],
            options={
                'ordering': ['scenario_id', 'stage', 'category', 'name'],
                'unique_together': {('scenario', 'stage', 'name', 'unit', 'category')},
            },
        ),
    ]
