# Generated by Django 5.2.9 on 2025-12-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_ingredient_dishingredient_dish_ingredients'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='shopping_lists', to='events.dish'),
        ),
    ]
