# Generated by Django 5.2.9 on 2025-12-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppinglist_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='intensity',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=16),
        ),
    ]
