# Generated by Django 5.2.9 on 2025-12-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_shoppinglist_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='is_bought',
            field=models.BooleanField(default=False, help_text='Позначено як куплено'),
        ),
    ]
