# Generated by Django 5.2.9 on 2025-12-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_cocktail_category_and_strength'),
        ('shopping', '0004_shoppingitem_is_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='cocktails',
            field=models.ManyToManyField(blank=True, related_name='shopping_lists', to='recipes.cocktail'),
        ),
        migrations.AlterField(
            model_name='scenariosupplytemplate',
            name='category',
            field=models.CharField(choices=[('alcohol', 'Алкоголь'), ('food', 'Їжа'), ('water', 'Вода'), ('ice', 'Лід'), ('other', 'Інше')], default='other', max_length=16),
        ),
        migrations.AlterField(
            model_name='scenariosupplytemplate',
            name='stage',
            field=models.CharField(choices=[('prep', 'Підготовка'), ('during', 'Під час'), ('recovery', 'Відновлення')], max_length=16),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='category',
            field=models.CharField(choices=[('alcohol', 'Алкоголь'), ('food', 'Їжа'), ('water', 'Вода'), ('ice', 'Лід'), ('other', 'Інше')], default='other', max_length=16),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='intensity',
            field=models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока')], default='medium', max_length=16),
        ),
    ]
